### ISSUE TITLE
Add option to include platform fees

### ISSUE THREAD

**Issue by georgeappiah** [dolyanne/e-levy-calculator-gh#1]
Thanks for providing this.

But from my understanding, the e-levy fee is never charged alone: it's always in addition to the platform-specific fees.

So it would be awesome if you could add the option to include the platform fees for the common providers/scenarios (or even a free-form to manually enter the % fee charged by the platform).

This way, users can see a complete picture of the fee they'll be paying in a transfer: e-levy plus platform fees.

**Comment by taytonyeli** [comment]
Thanks @georgeappiah for the suggestion. We're looking into this.

**Comment by jaedag** [comment]
I was just thinking this. You guys don't mind if we submit a PR right?

**Comment by jaedag** [comment]
Also random tip

Assuming @dolyanne and Dorothy Opoku are the same person, she needs to run 

`git config --global user.email "email@example.com"`

On her dev machine

So that her commits get matched to her GitHub profile. Otherwise then she misses out on all those GitHub contribution graph points.

**Comment by dolyanne** [comment]
@jaedag thanks for the tip, I thought I fixed that. But clearly I didn't . Tried it, it worked thank you 😃
